name: Audit dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]

permissions: {}

jobs:
  audit_deps:
    if: ${{ github.repository_owner == 'rolv-apneseth' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
